app:
  kafka:
    bootstrap-servers: localhost:9092
    room-topic-name: room-events
    thermometer-topic-name: thermometer-events

spring:
  kafka:
    producer:
      properties:
        spring.json.add.type.headers: false